# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='\u0410\u0442\u0430\u043b\u044b\u0448\u044b')),
                ('image', models.ImageField(null=True, upload_to='\u041d\u043e\u0432\u043e\u0441\u0442\u0438', verbose_name='\u0421\u04af\u0440\u04e9\u0442')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430\u0441\u044b')),
                ('likes', models.IntegerField(default=0, verbose_name='\u0416\u0430\u043a\u0442\u044b\u0440\u044b\u043b\u0434\u044b')),
            ],
            options={
                'verbose_name': '\u0416\u0430\u04a3\u044b\u043b\u044b\u043a',
                'verbose_name_plural': '\u0416\u0430\u04a3\u044b\u043b\u044b\u043a\u0442\u0430\u0440',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0410\u0442\u044b')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mysite.Article', verbose_name='\u0416\u0430\u04a3\u044b\u043b\u044b\u043a\u0442\u044b\u043d \u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439\u0438')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439\u043b\u0435\u0440',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_ms')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nazgul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0410\u0442\u044b')),
            ],
            options={
                'verbose_name': '\u0410\u043b\u044c\u0431\u043e\u043c',
                'verbose_name_plural': '\u0410\u043b\u044c\u0431\u043e\u043c\u0434\u043e\u0440',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Album', verbose_name='\u0421\u04af\u0440\u04e9\u0442')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mysite.Property', verbose_name='C\u04af\u0440\u04e9\u0442')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(to='Mysite.Images'),
        ),
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['last_name'],
                'proxy': True,
            },
            bases=('Mysite.person',),
        ),
    ]
