# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 12:50
from __future__ import unicode_literals

import Journal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '\u0414\u0435\u043d\u044c \u043d\u0435\u0434\u0435\u043b\u0438',
                'verbose_name_plural': '\u0414\u043d\u0438 \u043d\u0435\u0434\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=1, null=True, verbose_name='\u041a\u043b\u0430\u0441\u0441')),
                ('nominal', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='\u0410\u0442\u0430\u043b\u043c\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u0430\u0441\u0441',
                'verbose_name_plural': '\u041a\u043b\u0430\u0441\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='LessonsDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(to='Journal.Day', verbose_name='\u041a\u04af\u043d\u0434\u04e9\u0440')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0420\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(default='#', max_length=4, verbose_name='\u0411\u0430\u0430')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u041e\u0446\u0435\u043d\u043a\u0430',
                'verbose_name_plural': '\u041e\u0446\u0435\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u044c')),
                ('start', models.DateField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u0438')),
                ('finish', models.DateField(verbose_name='\u041a\u043e\u043d\u0435\u0446 \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u0438')),
            ],
            options={
                'verbose_name': '\u0427\u0435\u0442\u0432\u0435\u0440\u0442\u044c',
                'verbose_name_plural': '\u0427\u0435\u0442\u0432\u0435\u0440\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0433\u043e\u0434\u0430')),
                ('finish', models.DateField(verbose_name='\u041a\u043e\u043dwf \u0433\u043e\u0434\u0430')),
            ],
            options={
                'verbose_name': '\u0423\u0447\u0435\u0431\u043d\u044b\u0439 \u0433\u043e\u0434',
                'verbose_name_plural': '\u0423\u0447\u0435\u0431\u043d\u044b\u0435 \u0433\u043e\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='\u0410\u0442\u044b')),
                ('last_name', models.CharField(max_length=200, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(max_length=200, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('birthday', models.DateField(verbose_name='\u0422\u0443\u0443\u043b\u0433\u0430\u043d \u0436\u044b\u043b\u044b')),
                ('address', models.CharField(max_length=200, verbose_name='\u0414\u0430\u0440\u0435\u043a')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('mother_phone', models.CharField(max_length=200, verbose_name='\u0410\u043f\u0430\u0441\u044b\u043d\u044b\u043d \u043d\u043e\u043c\u0435\u0440\u0438')),
                ('father_phone', models.CharField(max_length=200, verbose_name='\u0410\u0442\u0430\u0441\u044b\u043d\u044b\u043d \u043d\u043e\u043c\u0435\u0440\u0438')),
                ('starosta', models.BooleanField(default=False, verbose_name='\u041a\u043b\u0430\u0441\u0441 \u0431\u0430\u0448\u0447\u044b\u0441\u044b')),
                ('image', models.FileField(blank=True, null=True, upload_to=Journal.models.image_upload_to, verbose_name='\u0421\u04af\u0440\u04e9\u0442')),
                ('current_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentGroup', to='Journal.Group', verbose_name='\u041a\u043b\u0430\u0441\u0441')),
            ],
            options={
                'verbose_name': '\u0423\u0447\u0435\u043d\u0438\u043a',
                'verbose_name_plural': '\u0423\u0447\u0435\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, choices=[('\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0442\u0438\u043a\u0430', '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0442\u0438\u043a\u0430'), ('\u0413\u0435\u043e\u0433\u0440\u0430\u0444\u0438\u044f', '\u0413\u0435\u043e\u0433\u0440\u0430\u0444\u0438\u044f'), ('\u0418\u0441\u0442\u043e\u0440\u0438\u044f', '\u0418\u0441\u0442\u043e\u0440\u0438\u044f'), ('\u041c\u0430\u0442\u0435\u043c\u0430\u0442\u0438\u043a\u0430', '\u041c\u0430\u0442\u0435\u043c\u0430\u0442\u0438\u043a\u0430'), ('\u0413\u0435\u043e\u043c\u0435\u0442\u0440\u0438\u044f', '\u0413\u0435\u043e\u043c\u0435\u0442\u0440\u0438\u044f'), ('\u0420\u0443\u0441\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a'), ('\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d\u0430', '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d\u0430'), ('\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a', '\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a'), ('\u0421\u043e\u0446\u0438\u043e\u043b\u043e\u0433\u0438\u044f', '\u0421\u043e\u0446\u0438\u043e\u043b\u043e\u0433\u0438\u044f'), ('\u0425\u0438\u043c\u0438\u044f', '\u0425\u0438\u043c\u0438\u044f'), ('\u0424\u0438\u0437\u0438\u043a\u0430', '\u0424\u0438\u0437\u0438\u043a\u0430'), ('\u0411\u0438\u043e\u043b\u043e\u0433\u0438\u044f', '\u0411\u0438\u043e\u043b\u043e\u0433\u0438\u044f')], max_length=200, null=True, verbose_name='\u0421\u0430\u0431\u0430\u043a ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Journal.Group', verbose_name='\u041a\u043b\u0430\u0441\u0441')),
                ('school_year', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Journal.SchoolYear', verbose_name='\u041e\u043a\u0443\u0443 \u0436\u044b\u043b\u044b')),
            ],
            options={
                'verbose_name': '\u0423\u0440\u043e\u043a',
                'verbose_name_plural': '\u0423\u0440\u043e\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='SubjectDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True, verbose_name='\u041a\u04af\u043d')),
                ('lessonsday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.LessonsDay')),
            ],
            options={
                'verbose_name': '\u0414\u0435\u043d\u044c',
                'verbose_name_plural': '\u0414\u043d\u0438',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_ms')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0423\u0447\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u0423\u0447\u0438\u0442\u0435\u043b\u044f',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Journal.Teacher', verbose_name='\u041c\u0443\u0433\u0430\u043b\u0438\u043c'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='school_year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Journal.SchoolYear'),
        ),
        migrations.AddField(
            model_name='point',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.Student', verbose_name='\u041e\u043a\u0443\u0443\u0447\u0443'),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(to='Journal.Student'),
        ),
        migrations.AddField(
            model_name='lessonsday',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.Quarter', verbose_name='\u0427\u0435\u0439\u0440\u0435\u043a'),
        ),
        migrations.AddField(
            model_name='lessonsday',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journal.Subject', verbose_name='\u0421\u0430\u0431\u0430\u043a'),
        ),
        migrations.AddField(
            model_name='group',
            name='school_year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Journal.SchoolYear', verbose_name='\u041e\u043a\u0443\u0443 \u0436\u044b\u043b\u044b'),
        ),
    ]
