# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-27 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='date',
            new_name='data',
        ),
    ]
