# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_auto_20160527_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='point',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Journal.Subject', verbose_name='\u0421\u0430\u0431\u0430\u043a'),
        ),
    ]
