# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0003_auto_20160602_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
