# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0004_auto_20160604_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(),
        ),
    ]
